Cambios en estructura del sitio web
MiguelAHz2/ServicesWpp pull request #3
Opened 2024-07-06 16:28 UTC by MiguelAHz2

**Cambios**
- Se añadió la estructura para la página Home.
- Se añadió la ruta Confirmation en el App.jsx
- Se creó una nueva pagina llamada Confirmation. 
- Se enlazó la página Confirmation para que al momento que se envié el form, redirija inmediatamente. 
- Se corrigió partes de la sintaxis en los archivos del proyecto (class a className, for a htmlFor)

2024-07-06 16:32 UTC, Deiverso-JM commented on src/App.jsx
> +import React from 'react'
No es necesario importar React en esta version actual - Corregir

2024-07-06 16:33 UTC, MiguelAHz2 commented on src/App.jsx
> +import React from 'react'
Eso estaba así cuando lo importé :V

2024-07-06 16:42 UTC, Deiverso-JM requested changes
Estoy notando que estas remplazando class a classname, lo que me indica que no hiciste pull actual de la rama develop para ver si tenias conflictos, recuerda que cada vez que hagas cambios o hagas nuevos elementos debes hacer un pull actual de la rama develop para ver si te genera conflictos y tomes los cambios nuevos de otros desarolladores

2024-07-06 16:42 UTC, Deiverso-JM commented on src/Components/Confirmation.jsx
> +import React from 'react';
No es necesario

2024-07-06 16:42 UTC, Deiverso-JM commented on src/Components/Confirmation.jsx
> +      <img src="/public/logo.png" alt="Logo" className="mx-auto mb-2" />
Logo no es una foto es un chulito de confirmacion - Cambiar por icono SVG o importar una etiqueta svg

2024-07-06 16:42 UTC, Deiverso-JM commented on src/App.jsx
> +import React from 'react'
No es necesario

2024-07-06 16:42 UTC, Deiverso-JM commented on src/Components/FormOrder.jsx
> +    const navigate = useNavigate();
Las ramas o issues van separadas, para cada cambio se debe crear un rama en otra palabras
- Estructura pagina - Rama 1
- Funcionalidad - Rama 2
- ETC..... Rama N

2024-07-06 16:42 UTC, Deiverso-JM commented on src/Components/Home.jsx
> +      <body className="flex items-center justify-center min-h-screen bg-gray-100">
Etiqueta body no correspondiente - Mala semantica de HTML  - Corregir

2024-07-12 21:08 UTC, MiguelAHz2 commented
> Estoy notando que estas remplazando class a classname, lo que me indica que no hiciste pull actual de la rama develop para ver si tenias conflictos, recuerda que cada vez que hagas cambios o hagas nuevos elementos debes hacer un pull actual de la rama develop para ver si te genera conflictos y tomes los cambios nuevos de otros desarolladores

2024-07-12 21:08 UTC, MiguelAHz2 commented on src/Components/Confirmation.jsx
> +import React from 'react';
Ok, corregido

2024-07-12 21:14 UTC, MiguelAHz2 commented on src/Components/Confirmation.jsx
> +      <img src="/public/logo.png" alt="Logo" className="mx-auto mb-2" />
Ok, corregido

2024-07-12 21:14 UTC, MiguelAHz2 commented on src/App.jsx
> +import React from 'react'
Ok, corregido

2024-07-12 21:16 UTC, MiguelAHz2 commented on src/Components/FormOrder.jsx
> +    const navigate = useNavigate();
Ok

2024-07-12 21:19 UTC, MiguelAHz2 commented on src/Components/Home.jsx
> +      <body className="flex items-center justify-center min-h-screen bg-gray-100">
Ok, corregido

2024-07-12 22:26 UTC, Deiverso-JM approved these changes
Ok, perfecto.

2024-07-12 22:27 UTC, merged